---
title: "Link daily air pollution data for MCC 792 cities"
author: "Rongbin Xu"
date: "24 June 2019"
output: html_document
---

```{r}
library(dplyr)
library(raster)
library("rgdal")
library("rgeos")
library(tmap)
library(stars)
library(cptcity)
library(sf)
library(sp)
library(tidyverse)
library(lubridate)
library(humidity)
library(data.table)
```

## daily wildfire and traffic pollution data
```{r}
climate_file<-list.files("S:/MNHS-SPHPM-EPM/GlobalAir/Global wildfire prediction/Predicted data/Global fire and total PM2.5 O3 0.25 2000-2019_v2/Predictor_data_monthly")
climate_path<-paste("S:/MNHS-SPHPM-EPM/GlobalAir/Global wildfire prediction/Predicted data/Global fire and total PM2.5 O3 0.25 2000-2019_v2/Predictor_data_monthly",climate_file,sep = "/")
system.time(r<-readRDS(climate_path[1]))##126s
r<-filter(r,date==unique(r$date)[1])%>%rename(x=lon,y=lat)
r1<-rasterFromXYZ(r[,c("x","y","temp_C")])
plot(r1)
```


## Get weight for each cell
```{r}
city_cells<-readRDS("MCC_792_cities_cell_numbers.rds")
all_grid_ID<-unique(city_cells$grid_id)
table(all_grid_ID%in%r$grid_id)
```


## Add population weight
```{r}
pop<-raster("S:/MNHS-SPHPM-EPM/GlobalAir/Global demographic and SES data/Worldpop/Unconstrained global mosaic 0.25 degree_ERA5_land gird/ppp_2000_025d.tif")
#pop
pop_data<-pop%>%as.data.frame(xy=T)

r_data<-r[,c("x","y","grid_id")]%>%
  left_join(pop_data)%>%
  filter(grid_id%in%all_grid_ID)
summary(r_data$ppp_2000_025d)

## Read all pop data
f_pop<-function(Y=2000){
  file.name<-paste("S:/MNHS-SPHPM-EPM/GlobalAir/Global demographic and SES data/Worldpop/Unconstrained global mosaic 0.25 degree_ERA5_land gird/ppp_",Y,"_025d.tif",sep = "")
  pop<-raster(file.name)%>%
    as.data.frame(xy=T)%>%
    right_join(r[,c("x","y","grid_id")])%>%
    filter(grid_id%in%all_grid_ID)%>%
    mutate(year=Y)
  names(pop)[3]<-"pop"
  return(pop[,c("grid_id","year","pop")])
}

All_pop_data<-lapply(2000:2019, f_pop)%>%
  bind_rows()

## Check if any zero weight region/city
for (i in 2000:2019) {
  city_pop<-All_pop_data%>%
    filter(year==i)%>%
    right_join(city_cells)%>%
    group_by(CityID)%>%
    summarize(total_pop=sum(pop))%>%ungroup()
  
  print(i)
  print(min(city_pop$total_pop)==0)
} ## no sero population city/region

```

## Link all required grid data 2000-2019
```{r}
## read file
f_read<-function(filename=Month_data$climate_file[1]){
  data<-readRDS(filename)%>%
    filter(grid_id%in%all_grid_ID)%>%
    dplyr::select(-x,-y)
  return(data)
}

Month_data<-readRDS("S:/MNHS-SPHPM-EPM/GlobalAir/Global wildfire prediction/Predicted data/Global fire and total PM2.5 O3 0.25 2000-2019_v2/Model and codes/All_ERA5_file_lists.rds")%>%
  group_by(Y,M)%>%
  summarise(n.files=n())%>%
  mutate(climate_file=paste("S:/MNHS-SPHPM-EPM/GlobalAir/Global wildfire prediction/Predicted data/Global fire and total PM2.5 O3 0.25 2000-2019_v2/Predictor_data_monthly/total_and_wildfire_PM25_O3_predictor_data",Y,M,".rds",sep = ""))

summary(Month_data)
```


## function for process one month data
```{r}
f_one_month<-function(i){
## read data
climate_data<-readRDS(Month_data$climate_file[i])%>%
  filter(grid_id%in%all_grid_ID)%>%
  dplyr::select(grid_id,date,temp_C,tmax,tmin,relative_humidity,perticipation_mm,pressure_hp,
                uvb)

## simple grid average for cities
city_data<-city_cells[,c("grid_id","CityID","weight")]%>%
  left_join(climate_data)

city_simple_av<-city_data%>%
  mutate(temp_C_W=temp_C*weight,
          tmax_W=tmax*weight,
          tmin_W=tmin*weight,
          relative_humidity_w=relative_humidity*weight,
          perticipation_mm_W=perticipation_mm*weight,
          pressure_hp_w=pressure_hp*weight,
          uvb_w=uvb*weight
         )%>%
    group_by(CityID,date)%>%
    summarise(tmean=sum(temp_C_W)/sum(weight),
              tmax=sum(tmax_W)/sum(weight),
              tmin=sum(tmin_W)/sum(weight),
              RH=sum(relative_humidity_w)/sum(weight),
              rainfall=sum(perticipation_mm_W)/sum(weight),
              pressure=sum(pressure_hp_w)/sum(weight),
              uvb=sum(uvb_w)/sum(weight))%>%
  ungroup()

## calculate city population weighted average
city_pop_av<-All_pop_data%>%
  filter(year==year(unique(city_data$date)))%>%
  right_join(city_data)%>%
  mutate(weight=weight*pop)%>% ## recalculate the weight by adding population weight  
  mutate(temp_C_W=temp_C*weight,
          tmax_W=tmax*weight,
          tmin_W=tmin*weight,
          relative_humidity_w=relative_humidity*weight,
          perticipation_mm_W=perticipation_mm*weight,
          pressure_hp_w=pressure_hp*weight,
          uvb_w=uvb*weight
         )%>%
    group_by(CityID,date)%>%
    summarise(tmean=sum(temp_C_W)/sum(weight),
              tmax=sum(tmax_W)/sum(weight),
              tmin=sum(tmin_W)/sum(weight),
              RH=sum(relative_humidity_w)/sum(weight),
              rainfall=sum(perticipation_mm_W)/sum(weight),
              pressure=sum(pressure_hp_w)/sum(weight),
              uvb=sum(uvb_w)/sum(weight))%>%
  ungroup()

  
  ## Save results
data_list<-list(city_simple_av,city_pop_av)

names(data_list)<-c("city_simple","city_pop_av")
return(data_list)
}
```
## Read and process all data
```{r}
system.time(sample_data<-f_one_month(1))##29s
lapply(sample_data,summary)## no problem
## read all files
## Parell process
library(doParallel)
detectCores()
cl <- makeCluster(10)
registerDoParallel(cl,cores = 10)
clusterEvalQ(cl, c(library(dplyr),library(lubridate)))
 ## define all input data or vars
clusterExport(cl,varlist = c("f_one_month","Month_data","all_grid_ID","All_pop_data","city_cells"),envir = environment())

system.time(MCC_data<-parLapply(cl = cl,1:240,f_one_month))##about 58min

# stop cores/cluster
stopCluster(cl)
```



## Save all data
```{r}
lapply(MCC_data,function(data.list) data.list$city_simple)%>%
  bind_rows()%>%
saveRDS(file="MCC_daily_weather_792_cities_0.25grid_simple_average_2000_2019.rds")
MCC_simple<-readRDS("MCC_daily_weather_792_cities_0.25grid_simple_average_2000_2019.rds")
summary(MCC_simple) 

lapply(MCC_data,function(data.list) data.list$city_pop_av)%>%
  bind_rows()%>%
saveRDS(file="MCC_daily_weather_792_cities_0.25grid_pop_weighted_average_2000_2019.rds")
MCC_pop_av<-readRDS("MCC_daily_weather_792_cities_0.25grid_pop_weighted_average_2000_2019.rds")
summary(MCC_pop_av)


```



