---
title: "PM25_extract"
author: "Tingting"
date: "April 12, 2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r pressure, echo=FALSE}
#Import libraries
library(ncdf4)
library(raster)
library(rgdal)
require(sf)
library(ggplot2)
```

```{r}
#1. Introduce .nc file. 
#Varname is the dimension
path = "S:/MNHS-SPHPM-EPM/ChildrenEnviro/Other_Papers/Xiang/"

nc_data<-nc_open(paste(path,"ECHAP_PM2.5_D1K_2016001_V3.nc", sep =""))
names(nc_data$var)

#1.1 reads the latitudes, longitudes, and saves them in memory.
lon <- ncvar_get(nc_data, "Lon") # stored
lat <- ncvar_get(nc_data, "Lat", verbose = F)

head(lon) # look at the first few entries in the longitude vector
```

```{r}
#1.2  store the PM2.5 in a 2-dimensional matrix
pm <- ncvar_get(nc_data, "PM2.5")
```

```{r}
#1.3 All done reading in the data. We can close the netCDF file.
nc_close(nc_data) 
```

```{r}
#2. Convert PM2.5 data into a raster layer with the crs.
r <- raster(t(pm), xmn=min(lon), xmx=max(lon), ymn=min(lat), ymx=max(lat),
            crs=CRS("+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs+ towgs84=0,0,0"))
# write raster to a local drive, if needed
#writeRaster(r, file = paste(path,"test2016.tif",sep=""), format = 'GTiff', overwrite = TRUE)
```

```{r}
#3. Read the data with lat and lon, as a shape point. if you don't have a point shapefile, then no need to run this.
pts<-read_sf(paste(path, "sh_pts_v.shp", sep = ""))
```

```{r}
# if you only have a .csv data with lat/lon, we can
#3.1 Create shp point from a .csv with 'Longitude' and 'Latitude'
pts <- read.csv(paste(path, "shanghai-address1.csv",sep = ""))
address<-address[which(!is.na(address$Longitude)),]  # remove null data
coordinates(address)= ~ Longitude+ Latitude
```

```{r}
#3.2 plot a raster layer of PM2.5, add a polygon and points
plot(r)
#plot(sh, fill = NA, color = "red", add= T)
plot(pts, fill = "red", add = T)
```

```{r}
#4. Extract raster value by points 
rasValue <- extract(r, pts)

#4.1 Combine raster values with point and save as a CSV file.
combinePointValue<- cbind(pts,rasValue)
combinePointValue <- as.data.frame(combinePointValue)[,-c(6)]
names(combinePointValue)[5]<-"PM25_2016001"
write.table(combinePointValue,file= paste(path, "test1.csv"), append=FALSE, sep= ",", row.names = FALSE, col.names=TRUE)
```

```{r}
## Iteration 
library(plyr)

# 1. unzip files 
# get all the zip files
path = "S:/MNHS-SPHPM-EPM/ChildrenEnviro/Other_Papers/Xiang/"

zipF <- list.files(path, pattern = "*.zip", full.names = TRUE)

# unzip all your files
outDir = paste(path, "test",sep = "")
ldply(.data = zipF, .fun = unzip, exdir = outDir)


# get the files
files <- list.files(path = outDir, pattern = "*.nc")

# read the csv files
#my_data <- ldply(.data = csv_files, .fun = read.csv)

nc_data<-nc_open(paste(outDir,files[i], sep ="/"))
names(nc_data$var)

```
